services:
    db:
        image: postgres:17
        container_name: ${COMPOSE_PROJECT_NAME}.db.docker
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - 127.0.0.1:${DATABASE_PORT}:5432
        volumes:
            - db.data:/var/lib/postgresql/data

    redis_cache:
        image: redis:8.0-M03-alpine
        container_name: ${COMPOSE_PROJECT_NAME}.redis_cache.docker
        restart: unless-stopped
        command: redis-server --requirepass ${REDIS_CACHE_PASS}
        ports:
            - 127.0.0.1:${REDIS_CACHE_PORT}:6379
        volumes:
            - redis_cache.data:/data

volumes:
    db.data:
    redis_cache.data:
