services:
    db:
        image: postgres:17
        container_name: ${COMPOSE_PROJECT_NAME}.db.docker
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - 127.0.0.1:${DATABASE_PORT}:5432
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
